/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package average.multithread

import java.io.BufferedReader
import java.io.File
import java.io.FileReader
import java.io.InputStream
import kotlin.test.Test

class AppTest {
//    @Test fun testAverage() {
//        val file = File("src/main/resources/input.csv")
//        val buffer = BufferedReader(FileReader(file))
//        while (buffer.readLine() != null) {
//            val line = buffer.readLine()
//            println(">> $line")
//        }
//    }
}
