/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/6.8/samples
 */

val projectVersion: String by ext
val kotlinTestVersion: String by ext
val mockkVersion: String by ext
val junitJupiterVersion: String by ext
val kotlinCoroutinesVersion: String by ext
val javaxInjectVersion: String by ext
val springBootVersion: String by ext
val jacksonVersion: String by ext
val kotlinLogginVersion: String by ext

java.sourceCompatibility = JavaVersion.VERSION_11

/**
 * SPRING BOOT SETUP
 */
//plugins {
//    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
//    id("org.jetbrains.kotlin.jvm") version "1.4.20"
//    id("io.spring.dependency-management") version "1.0.9.RELEASE"
//    id("org.springframework.boot") version "2.4.4" apply false
//    kotlin("plugin.spring") version "1.4.31"
//    java
//}
//
//subprojects {
//    apply {
//        plugin("kotlin")
//        plugin("io.spring.dependency-management")
//        plugin("org.jetbrains.kotlin.plugin.spring")
//    }
//
//    dependencyManagement {
//        imports {
//            mavenBom("org.springframework.boot:spring-boot-dependencies:$springBootVersion")
//        }
//        dependencies {
//            dependency("io.kotlintest:kotlintest-runner-junit5:$kotlinTestVersion")
//            dependency("io.mockk:mockk:$mockkVersion")
//            dependency("org.junit.jupiter:junit-jupiter:$junitJupiterVersion")
//            dependency("org.jetbrains.kotlinx:kotlinx-coroutines-core:$kotlinCoroutinesVersion")
//            dependency("org.jetbrains.kotlinx:kotlinx-coroutines-test:$kotlinCoroutinesVersion")
//            dependency("com.fasterxml.jackson.core:jackson-core:$jacksonVersion")
//            dependency("com.fasterxml.jackson.module:jackson-module-kotlin:$jacksonVersion")
//            dependency("com.fasterxml.jackson.datatype:jackson-datatype-jdk8:$jacksonVersion")
//            dependency("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:$jacksonVersion")
//            dependency("io.github.microutils:kotlin-logging-jvm:$kotlinLogginVersion")
//        }
//    }
//
//    dependencies {
//        implementation(platform("org.jetbrains.kotlin:kotlin-bom"))
//        implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
//        implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core")
//        implementation("io.github.microutils:kotlin-logging-jvm")
//
//        testImplementation("io.mockk:mockk")
//        testImplementation("org.junit.jupiter:junit-jupiter")
//        testImplementation("io.kotlintest:kotlintest-runner-junit5")
//        testImplementation("org.jetbrains.kotlinx:kotlinx-coroutines-test:$kotlinCoroutinesVersion")
//    }
//}

/**
 * DEFAULT
 */
plugins {
    id("org.jetbrains.kotlin.jvm") version "1.4.20"
    java
}

subprojects {
    apply {
        plugin("kotlin")
    }
    dependencies {
        implementation(platform("org.jetbrains.kotlin:kotlin-bom"))
        implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
        implementation("io.kotlintest:kotlintest-runner-junit5:$kotlinTestVersion")
        implementation("io.mockk:mockk:$mockkVersion")
        implementation("org.junit.jupiter:junit-jupiter:$junitJupiterVersion")
    }
}


allprojects {
    repositories {
        mavenCentral()
        mavenLocal()
    }

    tasks {
        test {
            useJUnitPlatform()
        }
    }
}

repositories {
    // Use JCenter for resolving dependencies.
    jcenter()
}
